### ISSUE TITLE
`xdotool key F*` breaks after the update of `xkeyboard-config`

### ISSUE THREAD

**Issue by Tomaqa** [jordansissel/xdotool#491]
After upgrading `xkeyboard-config (2.45-1 => 2.46-1)`, `xdotool key F*` or combinations such as `xdotool key super+F3` do not work anymore.

Also reported by another guy here: https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/554
However, the keys work properly outside of `xdotool`

Using version 3.20211022.1-2 on Arch Linux 6.12.53-1 LTS.
I verified that the behavior was independent of the following upgrades:
linux-lts 6.6.28-1 -> 6.12.53-1
libxkbcommon-x11 1.11.0-1 -> 1.12.2-1
linux-firmware 20250917-1 -> 20251011-1

**Comment by jordansissel** [comment]
As for why this problem happens now and correlates to the xkeyboard-config version change, I don't know, yet.

**Comment by wismill** [comment]
The issue is that the code does not check if the level 0 can be reached without modifiers, because this entry is discarded from the `XkbKTMapEntryRec` table at keymap compilation. So it worked before only by chance, because no entry targeted level 0. Now that the key type has been modified with additional `preserve` entries to fix a bug, you get such entries and xdotool does not use the canonical entry (without modifiers) anymore.

**Comment by jpka-** [comment]
Hello. 
I can confirm that `Alt_L` is added to _F*_ keys now. Tested with Archlinux. With `downgrade` from AUR, using `downgrade xkeyboard-config`, correct behavior restored.
Thanks.

**Comment by jordansissel** [comment]
> this entry is discarded from the XkbKTMapEntryRec table at keymap compilation

I am able to observe this, indeed! And it explains why xdotool gets the incorrect information.

From what I've now read and observed, the XkbDescPtr is an incomplete and *sparse* structure representing the keyboard mapping where some key mappings are simply absent (for reasons I haven't found documented). The documentation says of these absent key mappings:

> Any combination of modifiers not explicitly listed somewhere in the map yields shift level one.

This was the key to figuring out what an absent entry means.

So for these absent-entries, we must assume shift level one, and as @wismill noted, `xkbcomp` will delete level 1 entries when compiling the keymap. It'd be neat to know the history behind why some entries are absent in the struct even if defined by the keymap.

I've made a PR which hopefully solves this. It works for me testing both versions of xkeyboard-config and the test suite passes - https://github.com/jordansissel/xdotool/pull/493

**Comment by ionenwks** [comment]
> I've made a PR which hopefully solves this. It works for me testing both versions of xkeyboard-config and the test suite passes - [#493](https://github.com/jordansissel/xdotool/pull/493)

I've just tried the PR but it doesn't seem to help for me (just in case, note that when changing xkeyboard-config version, seems need to restart X for the change to take effect).

In case it may help, I seen the PR has a DEBUG env var check, so I went ahead and set it:
```
$ DEBUG=1 xdotool key F3
XTEST enabled.
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Escape) = keycode 9 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(1) = keycode 10 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(exclam) = keycode 10 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(2) = keycode 11 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(at) = keycode 11 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(3) = keycode 12 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(numbersign) = keycode 12 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(4) = keycode 13 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(dollar) = keycode 13 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(5) = keycode 14 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(percent) = keycode 14 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(6) = keycode 15 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(asciicircum) = keycode 15 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(7) = keycode 16 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(ampersand) = keycode 16 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(8) = keycode 17 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(asterisk) = keycode 17 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(9) = keycode 18 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(parenleft) = keycode 18 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(0) = keycode 19 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(parenright) = keycode 19 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(minus) = keycode 20 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(underscore) = keycode 20 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(equal) = keycode 21 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(plus) = keycode 21 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(BackSpace) = keycode 22 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(BackSpace) = keycode 22 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(Tab) = keycode 23 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(ISO_Left_Tab) = keycode 23 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(q) = keycode 24 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(Q) = keycode 24 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(w) = keycode 25 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(W) = keycode 25 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(e) = keycode 26 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(E) = keycode 26 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(r) = keycode 27 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(R) = keycode 27 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(t) = keycode 28 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(T) = keycode 28 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(y) = keycode 29 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(Y) = keycode 29 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(u) = keycode 30 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(U) = keycode 30 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(i) = keycode 31 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(I) = keycode 31 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(o) = keycode 32 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(O) = keycode 32 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(p) = keycode 33 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(P) = keycode 33 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(bracketleft) = keycode 34 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(braceleft) = keycode 34 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(bracketright) = keycode 35 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(braceright) = keycode 35 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Return) = keycode 36 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Control_L) = keycode 37 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(a) = keycode 38 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(A) = keycode 38 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(s) = keycode 39 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(S) = keycode 39 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(d) = keycode 40 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(D) = keycode 40 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(f) = keycode 41 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(F) = keycode 41 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(g) = keycode 42 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(G) = keycode 42 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(h) = keycode 43 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(H) = keycode 43 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(j) = keycode 44 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(J) = keycode 44 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(k) = keycode 45 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(K) = keycode 45 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(l) = keycode 46 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(L) = keycode 46 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(semicolon) = keycode 47 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(colon) = keycode 47 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(apostrophe) = keycode 48 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(quotedbl) = keycode 48 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(grave) = keycode 49 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(asciitilde) = keycode 49 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Shift_L) = keycode 50 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(backslash) = keycode 51 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(bar) = keycode 51 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(z) = keycode 52 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(Z) = keycode 52 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(x) = keycode 53 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(X) = keycode 53 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(c) = keycode 54 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(C) = keycode 54 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(v) = keycode 55 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(V) = keycode 55 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(b) = keycode 56 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(B) = keycode 56 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(n) = keycode 57 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(N) = keycode 57 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: ALPHABETIC) Symbol(m) = keycode 58 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Caps[2]] (KT: ALPHABETIC) Symbol(M) = keycode 58 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(comma) = keycode 59 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(less) = keycode 59 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(period) = keycode 60 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(greater) = keycode 60 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(slash) = keycode 61 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(question) = keycode 61 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Shift_R) = keycode 62 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(KP_Multiply) = keycode 63 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(KP_Multiply) = keycode 63 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(KP_Multiply) = keycode 63 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(KP_Multiply) = keycode 63 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86ClearGrab) = keycode 63 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Alt_L) = keycode 64 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(space) = keycode 65 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Caps_Lock) = keycode 66 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F1) = keycode 67 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F1) = keycode 67 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F1) = keycode 67 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F1) = keycode 67 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_1) = keycode 67 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F2) = keycode 68 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F2) = keycode 68 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F2) = keycode 68 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F2) = keycode 68 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_2) = keycode 68 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F3) = keycode 69 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F3) = keycode 69 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F3) = keycode 69 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F3) = keycode 69 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_3) = keycode 69 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F4) = keycode 70 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F4) = keycode 70 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F4) = keycode 70 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F4) = keycode 70 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_4) = keycode 70 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F5) = keycode 71 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F5) = keycode 71 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F5) = keycode 71 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F5) = keycode 71 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_5) = keycode 71 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F6) = keycode 72 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F6) = keycode 72 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F6) = keycode 72 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F6) = keycode 72 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_6) = keycode 72 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F7) = keycode 73 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F7) = keycode 73 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F7) = keycode 73 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F7) = keycode 73 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_7) = keycode 73 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F8) = keycode 74 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F8) = keycode 74 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F8) = keycode 74 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F8) = keycode 74 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_8) = keycode 74 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F9) = keycode 75 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F9) = keycode 75 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F9) = keycode 75 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F9) = keycode 75 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_9) = keycode 75 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F10) = keycode 76 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F10) = keycode 76 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F10) = keycode 76 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F10) = keycode 76 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_10) = keycode 76 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Num_Lock) = keycode 77 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Scroll_Lock) = keycode 78 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_Home) = keycode 79 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_7) = keycode 79 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_Up) = keycode 80 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_8) = keycode 80 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_Prior) = keycode 81 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_9) = keycode 81 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(KP_Subtract) = keycode 82 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(KP_Subtract) = keycode 82 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(KP_Subtract) = keycode 82 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(KP_Subtract) = keycode 82 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Prev_VMode) = keycode 82 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_Left) = keycode 83 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_4) = keycode 83 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_Begin) = keycode 84 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_5) = keycode 84 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_Right) = keycode 85 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_6) = keycode 85 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(KP_Add) = keycode 86 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(KP_Add) = keycode 86 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(KP_Add) = keycode 86 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(KP_Add) = keycode 86 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Next_VMode) = keycode 86 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_End) = keycode 87 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_1) = keycode 87 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_Down) = keycode 88 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_2) = keycode 88 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_Next) = keycode 89 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_3) = keycode 89 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_Insert) = keycode 90 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_0) = keycode 90 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_Delete) = keycode 91 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_Decimal) = keycode 91 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(ISO_Level3_Shift) = keycode 92 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86TouchpadToggle) = keycode 93 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: FOUR_LEVEL) Symbol(less) = keycode 94 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: FOUR_LEVEL) Symbol(greater) = keycode 94 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: FOUR_LEVEL) Symbol(bar) = keycode 94 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: FOUR_LEVEL) Symbol(brokenbar) = keycode 94 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F11) = keycode 95 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F11) = keycode 95 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F11) = keycode 95 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F11) = keycode 95 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_11) = keycode 95 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F12) = keycode 96 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F12) = keycode 96 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F12) = keycode 96 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F12) = keycode 96 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_12) = keycode 96 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Katakana) = keycode 98 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Hiragana) = keycode 99 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Henkan_Mode) = keycode 100 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Hiragana_Katakana) = keycode 101 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Muhenkan) = keycode 102 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(KP_Enter) = keycode 104 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Control_R) = keycode 105 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(KP_Divide) = keycode 106 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(KP_Divide) = keycode 106 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(KP_Divide) = keycode 106 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(KP_Divide) = keycode 106 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Ungrab) = keycode 106 with mask:Control+Mod1, real_mods:4, vmods:Alt
[group 0, level Base[1]] (KT: PC_ALT_LEVEL2) Symbol(Print) = keycode 107 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Alt[2]] (KT: PC_ALT_LEVEL2) Symbol(Sys_Req) = keycode 107 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Alt_R) = keycode 108 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Linefeed) = keycode 109 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Home) = keycode 110 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Up) = keycode 111 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Prior) = keycode 112 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Left) = keycode 113 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Right) = keycode 114 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(End) = keycode 115 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Down) = keycode 116 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Next) = keycode 117 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Insert) = keycode 118 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Delete) = keycode 119 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioMute) = keycode 121 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioLowerVolume) = keycode 122 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioRaiseVolume) = keycode 123 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86PowerOff) = keycode 124 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(KP_Equal) = keycode 125 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(plusminus) = keycode 126 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: PC_CONTROL_LEVEL2) Symbol(Pause) = keycode 127 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Control[2]] (KT: PC_CONTROL_LEVEL2) Symbol(Break) = keycode 127 with mask:Control, real_mods:4, vmods:<none>
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86LaunchA) = keycode 128 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: KEYPAD) Symbol(KP_Decimal) = keycode 129 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Number[2]] (KT: KEYPAD) Symbol(KP_Decimal) = keycode 129 with mask:Mod2, real_mods:0, vmods:NumLock
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Hangul) = keycode 130 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Hangul_Hanja) = keycode 131 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Super_L) = keycode 133 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Super_R) = keycode 134 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Menu) = keycode 135 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Cancel) = keycode 136 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Redo) = keycode 137 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(SunProps) = keycode 138 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Undo) = keycode 139 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(SunFront) = keycode 140 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Copy) = keycode 141 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Open) = keycode 142 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Paste) = keycode 143 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Find) = keycode 144 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Cut) = keycode 145 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Help) = keycode 146 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86MenuKB) = keycode 147 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Calculator) = keycode 148 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Sleep) = keycode 150 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86WakeUp) = keycode 151 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Explorer) = keycode 152 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Send) = keycode 153 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Xfer) = keycode 155 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Launch1) = keycode 156 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Launch2) = keycode 157 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86WWW) = keycode 158 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86DOS) = keycode 159 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86ScreenSaver) = keycode 160 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86RotateWindows) = keycode 161 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86TaskPane) = keycode 162 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Mail) = keycode 163 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Favorites) = keycode 164 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86MyComputer) = keycode 165 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Back) = keycode 166 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Forward) = keycode 167 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Eject) = keycode 169 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Eject) = keycode 170 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioNext) = keycode 171 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(XF86AudioPlay) = keycode 172 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(XF86AudioPause) = keycode 172 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioPrev) = keycode 173 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: TWO_LEVEL) Symbol(XF86AudioStop) = keycode 174 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(XF86Eject) = keycode 174 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioRecord) = keycode 175 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioRewind) = keycode 176 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Phone) = keycode 177 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Tools) = keycode 179 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86HomePage) = keycode 180 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Reload) = keycode 181 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Close) = keycode 182 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86ScrollUp) = keycode 185 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86ScrollDown) = keycode 186 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(parenleft) = keycode 187 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(parenright) = keycode 188 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86New) = keycode 189 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Redo) = keycode 190 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Tools) = keycode 191 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Launch5) = keycode 192 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Launch6) = keycode 193 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Launch7) = keycode 194 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Launch8) = keycode 195 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Launch9) = keycode 196 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioMicMute) = keycode 198 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86TouchpadToggle) = keycode 199 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86TouchpadOn) = keycode 200 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: PC_SHIFT_SUPER_LEVEL2) Symbol(XF86TouchpadOff) = keycode 201 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Super[2]] (KT: PC_SHIFT_SUPER_LEVEL2) Symbol(XF86Assistant) = keycode 201 with mask:Shift+Mod4, real_mods:1, vmods:Super
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(ISO_Level5_Shift) = keycode 203 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Base[1]] (KT: TWO_LEVEL) keycode 204 is not bound at this level
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(Alt_L) = keycode 204 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) keycode 205 is not bound at this level
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(Meta_L) = keycode 205 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) keycode 206 is not bound at this level
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(Super_L) = keycode 206 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Base[1]] (KT: TWO_LEVEL) keycode 207 is not bound at this level
[group 0, level Shift[2]] (KT: TWO_LEVEL) Symbol(Hyper_L) = keycode 207 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioPlay) = keycode 208 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioPause) = keycode 209 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Launch3) = keycode 210 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Launch4) = keycode 211 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86LaunchB) = keycode 212 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Suspend) = keycode 213 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Close) = keycode 214 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioPlay) = keycode 215 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioForward) = keycode 216 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Print) = keycode 218 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86WebCam) = keycode 220 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioPreset) = keycode 221 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Mail) = keycode 223 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Messenger) = keycode 224 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Search) = keycode 225 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Go) = keycode 226 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Finance) = keycode 227 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Game) = keycode 228 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Shop) = keycode 229 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(Cancel) = keycode 231 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86MonBrightnessDown) = keycode 232 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86MonBrightnessUp) = keycode 233 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86AudioMedia) = keycode 234 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Display) = keycode 235 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86KbdLightOnOff) = keycode 236 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86KbdBrightnessDown) = keycode 237 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86KbdBrightnessUp) = keycode 238 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Send) = keycode 239 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Reply) = keycode 240 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86MailForward) = keycode 241 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Save) = keycode 242 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Documents) = keycode 243 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Battery) = keycode 244 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Bluetooth) = keycode 245 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86WLAN) = keycode 246 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86UWB) = keycode 247 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Next_VMode) = keycode 249 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86Prev_VMode) = keycode 250 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86MonBrightnessCycle) = keycode 251 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86BrightnessAuto) = keycode 252 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86DisplayOff) = keycode 253 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86WWAN) = keycode 254 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
[group 0, level Any[1]] (KT: ONE_LEVEL) Symbol(XF86RFKill) = keycode 255 with mask:<none>, real_mods:0, vmods:<none> [IMPLICIT] 
command: key
XTEST: Press modifier Mod1 using keycode 64
XTEST: Press key: keycode 69
XTEST: Release modifier Mod1 using keycode 64
XTEST: Release key: keycode 69
```

**Comment by jordansissel** [comment]
@ionenwks yes this PR should fix it, but as you found, it doesn’t for you. That debug output helps:

```
[group 0, level Base[1]] (KT: CTRL+ALT) Symbol(F3) = keycode 69 with mask:Mod1, real_mods:0, vmods:Alt
[group 0, level Shift[2]] (KT: CTRL+ALT) Symbol(F3) = keycode 69 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] (KT: CTRL+ALT) Symbol(F3) = keycode 69 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] (KT: CTRL+ALT) Symbol(F3) = keycode 69 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] (KT: CTRL+ALT) Symbol(XF86Switch_VT_3) = keycode 69 with mask:Control+Mod1, real_mods:4, vmods:Alt
```

Snippet from your debug output, xdotool believes that F3 must be sent with mod1 mask, so it sends two sequences. This is incorrect behavior, and I’ll see if I can reproduce it or narrow down why it’s behaving this way before this gets merged :)

**Comment by jpka-** [comment]
Hello. I also still see same behavior with current git, tested on two different machines (both are fresh Archlinux, XFCE): `Alt_L` added to `F1` key. 
Thanks.

**Comment by jordansissel** [comment]
I've updated #493 and believe I have fixed this issue. I tested on the latest Fedora 43 w/ xkeyboard-config 1.46

```
# DISPLAY=:0 LD_LIBRARY_PATH=./ DEBUG=1 ./xdotool search Test windowfocus key F3 |& grep 'keycode 69'
[group 0, level Base[1]] Symbol(F3) = keycode 69 with mask:<none>, real_mods:0, vmods:<none>
[group 0, level Shift[2]] Symbol(F3) = keycode 69 with mask:Shift, real_mods:1, vmods:<none>
[group 0, level AltGr[3]] Symbol(F3) = keycode 69 with mask:Mod5, real_mods:0, vmods:LevelThree
[group 0, level Shift AltGr[4]] Symbol(F3) = keycode 69 with mask:Shift+Mod5, real_mods:1, vmods:LevelThree
[group 0, level Ctrl+Alt[5]] Symbol(XF86Switch_VT_3) = keycode 69 with mask:Control+Mod1, real_mods:4, vmods:Alt
XTEST: Press key: keycode 69
XTEST: Release key: keycode 69
```

The above shows xdotool sending  F3 correctly as a single keycode with no modifiers (with my default keymap)

If any of you are able to try #493's latest commit, I would like feedback :)

(You'll need libXtst, libXinerama, and libxkbcommon + header files to compile xdotool)

I'll merge #493 once we get some feedback that this solves the problem.

**Comment by ionenwks** [comment]
> If any of you are able to try [#493](https://github.com/jordansissel/xdotool/pull/493)'s latest commit, I would like feedback :)

Thank you, it works as expected now using the PR's branch (using Gentoo).

**Comment by jordansissel** [comment]
New release includes this fix:  https://github.com/jordansissel/xdotool/releases/tag/v4.20251130.1
